{% set version = "1.1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinylp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinyLP_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyLP/shinyLP_{{ version }}.tar.gz
  sha256: 7f2be3a4babdd3c5a8a2adc12108e3c31c74b15cde300493bc06470602a54cea

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-shiny
  run:
    - r-base
    - r-shiny

test:
  commands:
    - $R -e "library('shinyLP')"           # [not win]
    - "\"%R%\" -e \"library('shinyLP')\""  # [win]

about:
  home: https://github.com/jasdumas/shinyLP
  license: MIT
  summary: Provides functions that wrap HTML Bootstrap components code to enable the design and layout of informative landing home pages for Shiny applications. This can lead to a better user experience for the users and writing less HTML for the developer.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
