{% set version = "1.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-shinylp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinyLP_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyLP/shinyLP_{{ version }}.tar.gz
  sha256: cc129b34048b1a00e18a24ccd6f1c357e7f13b084995c5010b0787af564bb1b1

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-shiny
  run:
    - r-base
    - r-shiny

test:
  commands:
    - $R -e "library('shinyLP')"           # [not win]
    - "\"%R%\" -e \"library('shinyLP')\""  # [win]

about:
  home: https://github.com/jasdumas/shinyLP
  license: MIT
  summary: Provides functions that wrap HTML Bootstrap components code to enable the design and layout of informative landing home pages for Shiny applications. This can lead to a better user experience for the users and writing less HTML for the developer.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
