appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XKW3fXxtGI8g4xBqijABOQtwctsodZsIEvFhuoS2z1EciuLU8xMff49ZKdsbuH6Oh4lh4nIVwIGvkXeNBzvWuhaENWvZSkfoWBEc2CFARncvQyenW4W+fTaP/GC/7da05y70ApNWD+7jvnXCoKJNG/fEuc39OPxIcZ3X29LwokIUar20UG/5aTja7h2d1MjViRiM3lH/DVhVKWnWj1GPl8ZBfvV7kNvquLg3YBAsbGlBU6zZwwX4hWGuUjZvzjuDdrh5KX4lmcOXPJcvR0LQiCI0w/oLSa4LgtW+pkZ0g3dgFuDr7MFmJDRub5+Va1Zd2b7xQoKckAFSASk33uuj0xw6mjHDkeiIwQObyFlbNA3jO+he/TKt76s63l+qdDbpQ2dTM93zaf+1BFhG0c36XGi/PS7qM4ABZZN8bBkKrj6++GHC/Gsd+qOzEMBJgsyNLmJS0Ame/LcA3liOZxon2xF/N+0S/XlkPp03OP5xDkGY7/nbsiM3nXdJnEZsosmGmt8/uGaDUL66KWKE79EJ0UANddcdtH2Y2M3219oZqfKdcBmejPb1IDShczBXhQd9gcTi9vNPvlmaJcZ2M59sWKHu/YyTrWiULyFZ9mPpxVJNtFcIrGcaYI550MKHSsMWIDrUFPZLnjZWWMexo7VTOH/HvgPg3izuwdoHKPFWIPs=}
